version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: retail_postgres
    restart: always
    environment:
      POSTGRES_USER: retail_user
      POSTGRES_PASSWORD: retail_pass
      POSTGRES_DB: retail_db
    ports:
      - "5432:5432"
    volumes:
      - ../../postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
